/*
 * JS for C1BecomePartnerPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '8d1c3d87-037c-46f1-9d3b-d76370ba131a';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "F1DeveloperPage",
    "location": "F1DeveloperPage.html"
}, {
    "name": "D0ComplaintPage",
    "location": "D0ComplaintPage.html"
}, {
    "name": "F2DownloadPage",
    "location": "F2DownloadPage.html"
}, {
    "name": "F0AboutUsPage",
    "location": "F0AboutUsPage.html"
}, {
    "name": "B0ShoutoutPage",
    "location": "B0ShoutoutPage.html"
}, {
    "name": "B1CheckShoutoutPage",
    "location": "B1CheckShoutoutPage.html"
}, {
    "name": "A0IndexPage",
    "location": "A0IndexPage.html"
}, {
    "name": "E0ContactUsPage",
    "location": "E0ContactUsPage.html"
}, {
    "name": "C1BecomePartnerPage",
    "location": "C1BecomePartnerPage.html"
}, {
    "name": "C0PartnersPage",
    "location": "C0PartnersPage.html"
}, {
    "name": "A0HomePage",
    "location": "A0HomePage.html"
}];

function C1BecomePartnerPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'C1BecomePartnerPage_mobilebutton_11',
        'mobilelabel_2': 'C1BecomePartnerPage_mobilelabel_2',
        'spacer_8': 'C1BecomePartnerPage_spacer_8',
        'mobilelabel_7': 'C1BecomePartnerPage_mobilelabel_7',
        'mobilelabel_3': 'C1BecomePartnerPage_mobilelabel_3',
        'spacer_6': 'C1BecomePartnerPage_spacer_6',
        'mobilelabel_4': 'C1BecomePartnerPage_mobilelabel_4',
        'mobilelabel_5': 'C1BecomePartnerPage_mobilelabel_5',
        'mobilelabel_10': 'C1BecomePartnerPage_mobilelabel_10'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'C1BecomePartnerPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var C1BecomePartnerPage_onLoad = function() {
            C1BecomePartnerPage_elementsExtraJS();

            C1BecomePartnerPage_deviceEvents();
            C1BecomePartnerPage_windowEvents();
            C1BecomePartnerPage_elementsEvents();
        };

    // screen window events


    function C1BecomePartnerPage_windowEvents() {

        $('#C1BecomePartnerPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function C1BecomePartnerPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function C1BecomePartnerPage_elementsExtraJS() {
        // screen (C1BecomePartnerPage) extra code

    };

    // screen elements handler


    function C1BecomePartnerPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#C1BecomePartnerPage").on("pagebeforeshow", "#C1BecomePartnerPage", function(event, ui) {
        Apperyio.CurrentScreen = "C1BecomePartnerPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    C1BecomePartnerPage_onLoad();
};

$(document).off("pagecreate", "#C1BecomePartnerPage").on("pagecreate", "#C1BecomePartnerPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    C1BecomePartnerPage_js();
});