/*
 * JS for F0AboutUsPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '8d1c3d87-037c-46f1-9d3b-d76370ba131a';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "F1DeveloperPage",
    "location": "F1DeveloperPage.html"
}, {
    "name": "D0ComplaintPage",
    "location": "D0ComplaintPage.html"
}, {
    "name": "F2DownloadPage",
    "location": "F2DownloadPage.html"
}, {
    "name": "F0AboutUsPage",
    "location": "F0AboutUsPage.html"
}, {
    "name": "B0ShoutoutPage",
    "location": "B0ShoutoutPage.html"
}, {
    "name": "B1CheckShoutoutPage",
    "location": "B1CheckShoutoutPage.html"
}, {
    "name": "A0IndexPage",
    "location": "A0IndexPage.html"
}, {
    "name": "E0ContactUsPage",
    "location": "E0ContactUsPage.html"
}, {
    "name": "C1BecomePartnerPage",
    "location": "C1BecomePartnerPage.html"
}, {
    "name": "C0PartnersPage",
    "location": "C0PartnersPage.html"
}, {
    "name": "A0HomePage",
    "location": "A0HomePage.html"
}];

function F0AboutUsPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'F0AboutUsPage_mobilebutton_2',
        'mobilegroupedbuttons_7': 'F0AboutUsPage_mobilegroupedbuttons_7',
        'mobilebutton_8': 'F0AboutUsPage_mobilebutton_8',
        'mobilelabel_4': 'F0AboutUsPage_mobilelabel_4',
        'mobilelabel_5': 'F0AboutUsPage_mobilelabel_5',
        'mobilelabel_6': 'F0AboutUsPage_mobilelabel_6'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'F0AboutUsPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var F0AboutUsPage_onLoad = function() {
            F0AboutUsPage_elementsExtraJS();

            F0AboutUsPage_deviceEvents();
            F0AboutUsPage_windowEvents();
            F0AboutUsPage_elementsEvents();
        };

    // screen window events


    function F0AboutUsPage_windowEvents() {

        $('#F0AboutUsPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function F0AboutUsPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function F0AboutUsPage_elementsExtraJS() {
        // screen (F0AboutUsPage) extra code

        /* UpdatePopupName */
        $("#F0AboutUsPage_UpdatePopupName").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function F0AboutUsPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#F0AboutUsPage_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("UpdatePopupName");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };

                }
            },
        }, '#F0AboutUsPage_mobileheader [name="mobilebutton_2"]');

        $(document).off("click", '#F0AboutUsPage_mobilecontainer [name="mobilebutton_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('F1DeveloperPage', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#F0AboutUsPage_mobilecontainer [name="mobilebutton_8"]');

    };

    $(document).off("pagebeforeshow", "#F0AboutUsPage").on("pagebeforeshow", "#F0AboutUsPage", function(event, ui) {
        Apperyio.CurrentScreen = "F0AboutUsPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    F0AboutUsPage_onLoad();
};

$(document).off("pagecreate", "#F0AboutUsPage").on("pagecreate", "#F0AboutUsPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    F0AboutUsPage_js();
});