/*
 * JS for F2DownloadPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '8d1c3d87-037c-46f1-9d3b-d76370ba131a';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "F1DeveloperPage",
    "location": "F1DeveloperPage.html"
}, {
    "name": "D0ComplaintPage",
    "location": "D0ComplaintPage.html"
}, {
    "name": "F2DownloadPage",
    "location": "F2DownloadPage.html"
}, {
    "name": "F0AboutUsPage",
    "location": "F0AboutUsPage.html"
}, {
    "name": "B0ShoutoutPage",
    "location": "B0ShoutoutPage.html"
}, {
    "name": "B1CheckShoutoutPage",
    "location": "B1CheckShoutoutPage.html"
}, {
    "name": "A0IndexPage",
    "location": "A0IndexPage.html"
}, {
    "name": "E0ContactUsPage",
    "location": "E0ContactUsPage.html"
}, {
    "name": "C1BecomePartnerPage",
    "location": "C1BecomePartnerPage.html"
}, {
    "name": "C0PartnersPage",
    "location": "C0PartnersPage.html"
}, {
    "name": "A0HomePage",
    "location": "A0HomePage.html"
}];

function F2DownloadPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'F2DownloadPage_mobilelabel_2',
        'mobilelabel_14': 'F2DownloadPage_mobilelabel_14',
        'spacer_21': 'F2DownloadPage_spacer_21',
        'mobilelabel_15': 'F2DownloadPage_mobilelabel_15',
        'spacer_16': 'F2DownloadPage_spacer_16',
        'mobilelabel_23': 'F2DownloadPage_mobilelabel_23',
        'mobilelabel_22': 'F2DownloadPage_mobilelabel_22',
        'mobilelabel_24': 'F2DownloadPage_mobilelabel_24',
        'spacer_25': 'F2DownloadPage_spacer_25',
        'mobilelabel_13': 'F2DownloadPage_mobilelabel_13',
        'mobilecollapsibleset_3': 'F2DownloadPage_mobilecollapsibleset_3',
        'mobilecollapsblock_4': 'F2DownloadPage_mobilecollapsblock_4',
        'mobilecollapsblockheader_5': 'F2DownloadPage_mobilecollapsblockheader_5',
        'mobilecollapsblockcontent_6': 'F2DownloadPage_mobilecollapsblockcontent_6',
        'mobilelabel_20': 'F2DownloadPage_mobilelabel_20',
        'mobilebutton_17': 'F2DownloadPage_mobilebutton_17',
        'mobilecollapsblock_7': 'F2DownloadPage_mobilecollapsblock_7',
        'mobilecollapsblockheader_8': 'F2DownloadPage_mobilecollapsblockheader_8',
        'mobilecollapsblockcontent_9': 'F2DownloadPage_mobilecollapsblockcontent_9',
        'mobilebutton_18': 'F2DownloadPage_mobilebutton_18',
        'mobilecollapsblock_10': 'F2DownloadPage_mobilecollapsblock_10',
        'mobilecollapsblockheader_11': 'F2DownloadPage_mobilecollapsblockheader_11',
        'mobilecollapsblockcontent_12': 'F2DownloadPage_mobilecollapsblockcontent_12',
        'mobilebutton_19': 'F2DownloadPage_mobilebutton_19'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'F2DownloadPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var F2DownloadPage_onLoad = function() {
            F2DownloadPage_elementsExtraJS();

            F2DownloadPage_deviceEvents();
            F2DownloadPage_windowEvents();
            F2DownloadPage_elementsEvents();
        };

    // screen window events


    function F2DownloadPage_windowEvents() {

        $('#F2DownloadPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function F2DownloadPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function F2DownloadPage_elementsExtraJS() {
        // screen (F2DownloadPage) extra code

        /* mobilecollapsblock_4 */

        $("#F2DownloadPage_mobilecollapsblock_4 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_7 */

        $("#F2DownloadPage_mobilecollapsblock_7 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_10 */

        $("#F2DownloadPage_mobilecollapsblock_10 .ui-collapsible-heading-toggle").attr("tabindex", "1");

    };

    // screen elements handler


    function F2DownloadPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#F2DownloadPage_mobilecontainer [name="mobilebutton_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://drive.google.com/file/d/0B05bWc7njQmeRlphYUVoUkhmOUk/view?usp=sharing', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                }
            },
        }, '#F2DownloadPage_mobilecontainer [name="mobilebutton_17"]');

    };

    $(document).off("pagebeforeshow", "#F2DownloadPage").on("pagebeforeshow", "#F2DownloadPage", function(event, ui) {
        Apperyio.CurrentScreen = "F2DownloadPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    F2DownloadPage_onLoad();
};

$(document).off("pagecreate", "#F2DownloadPage").on("pagecreate", "#F2DownloadPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    F2DownloadPage_js();
});